name: Continuous integration
on: 
 push:
   branches:
     - develop
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      arangodb:
        image: arangodb:3.3.23
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
            go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
            go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t dictybase/modware-annotation:develop-$(git rev-parse --short HEAD) -f build/package/Dockerfile .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    env:
      KUBEPATH: ${GITHUB_WORKSPACE}/.kube
      KUBECONFIG: ${KUBEPATH}/dictykube
      PROJECT_ID: ${{ secrets.DEV_KUBERNETES_PROJECT }}
      APPLICATION_CREDENTIALS: ${{ secrets.DEV_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: create config folder
        run: mkdir -p ${KUBEPATH}
      - name: retrieve kubernetes credentials
        uses: actions-hub/gcloud@master
        with:
          args: container clusters get-credentials ${{ secrets.DEVSIDD_CLUSTER_NAME }} --zone ${{ secrets.DICTY_ZONE }} --project ${{ secrets.DEV_KUBERNETES_PROJECT }}
